### ISSUE TITLE
long loading

### ISSUE THREAD

**Issue by NikiHard** [danimahardhika/wallpaperboard#107]
I noticed that if there are a lot of wallpapers in json, then the application is loaded for a long time
I have 6000 wallpapers, the first launch is long, and the subsequent ones too

**Comment by danimahardhika** [comment]
It's just the latest wallpaper part. If you swipe to another tab you will see the wallpapers already loaded there.

**Comment by NikiHard** [comment]
when a user opens the app, he observes loading of 30 seconds, Can it is possible as that to accelerate?

**Comment by danimahardhika** [comment]
Let me try it first, send your app or json via hangouts
