### ISSUE TITLE
cant run on emulator

### ISSUE THREAD

**Issue by fath1993** [danimahardhika/wallpaperboard#110]
Hi. after importing this app to android studio and update all thing it need, gradle do his job and project build successfully. but after that i cant run this app on emulator becuse android studiu dosen't find app to run. no idea what is this problem becuse other android project that i download from github and import to android studio work fine.
in manifest i check and there isn't any luncher activity. anyway i'm a little noob at this thing. if you may please help.
thanks.

**Comment by danimahardhika** [comment]
Because you are importing the wrong project. Read the wiki site first https://github.com/danimahardhika/wallpaperboard/wiki/Setup
