### ISSUE TITLE
Wallpaper Set 

### ISSUE THREAD

**Issue by pavelsust** [danimahardhika/wallpaperboard#129]
i want to set wallpaper just using.. 

public class MainActivity extends AppCompatActivity {

    Wallpaper wallpaper = Wallpaper.Builder().build();
    RectF rectF = null;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);

        WallpaperApplyTask.prepare(getApplicationContext())
                .wallpaper(wallpaper)
                .to(WallpaperApplyTask.Apply.HOMESCREEN)
                .start(AsyncTask.THREAD_POOL_EXECUTOR);

    }

}

I have initialized  wallpaper link in 

 public Wallpaper build() {
            Wallpaper wallpaper = new Wallpaper("Name", "Author", "https://images.pexels.com/photos/257360/pexels-photo-257360.jpeg", "https://images.pexels.com/photos/257360/pexels-photo-257360.jpeg", "Category", "Adon");
            wallpaper.setId(mId);
            wallpaper.setDimensions(mDimensions);
            wallpaper.setFavorite(mIsFavorite);
            wallpaper.setMimeType(mMimeType);
            wallpaper.setSize(mSize);
            wallpaper.setColor(mColor);
            return wallpaper;
        }

But it says wallpaer wallpaper can't set. How i can get this

**Comment by danimahardhika** [comment]
See the log cat

Why would you need another activity just to apply wallpaper

**Comment by pavelsust** [comment]
Thanks i i solved this issue. The error was if i just want to set wallpaper i have to config Universal Image Loader in AppController which extends Application class.

**Comment by pavelsust** [comment]
I am developing a custom application using your core features and it's also open source. 
Now i am facing a issue 

     @Override
        public void onClick(View v) {
            int position = getAdapterPosition();
            int id = v.getId();
            if (id == R.id.card){

                    try {
                        Bitmap bitmap = null;
                        if (imageView.getDrawable() != null) {
                            bitmap = ((BitmapDrawable) imageView.getDrawable()).getBitmap();
                        }

                        final Intent intent = new Intent(context.getApplicationContext(), ImageShowActivity.class);
                        intent.putExtra("url", itemsArrayList.get(position).getLink());
                        intent.setFlags(Intent.FLAG_ACTIVITY_SINGLE_TOP);
                        intent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);

                        ActivityTransitionLauncher.with((AppCompatActivity) context.getApplicationContext())
                                .from(imageView, "img")
                                .image(bitmap)
                                .launch(intent);

                    } catch (Exception e) {
                        e.printStackTrace();

                    }

                }
            }


On the other activity i have received it using 

          mExitTransition = ActivityTransition
                        .with(getIntent())
                       .to(this, imageView,"img")
                       .duration(300)
                       .start(savedInstanceState);


But the problem is when i click the card it doesn't open new activity. And from log i can see a error which is. 

         java.lang.ClassCastException: com.example.lolipop.testwallpaper.AppController cannot be cast to android.support.v7.app.AppCompatActivity


This is my Appcontroller 


public class AppController extends Application {

    public static Context context;
    private static AppController mInstance;

    public static Context getContext() {
        return AppController.context;
    }

    public static synchronized AppController getInstance() {
        return mInstance;
    }

    @Override
    public void onCreate() {
        super.onCreate();
        mInstance = this;
        AppController.context = getApplicationContext();
        if (!ImageLoader.getInstance().isInited())
            ImageLoader.getInstance().init(ImageConfig.getImageLoaderConfiguration(this));

    }

}

**Comment by danimahardhika** [comment]
Wrong context
