### ISSUE TITLE
Wallpapers not updated on json file update

### ISSUE THREAD

**Issue by SplashitApp** [danimahardhika/wallpaperboard#130]
App keeps on says on every refresh and app launch "Unable to check new wallpapers" I have used G drive and Github link both for json file, Only thing solves this by clearing data of app.

**Comment by danimahardhika** [comment]
That means there's something wrong with your json or your json doesn't match with the app config

**Comment by SplashitApp** [comment]
I am using default config, JSON file refreshes but only on clearing app data, If you want to see my JSON file then let me know where to send it. I will be happy if the fault is mine.

**Comment by danimahardhika** [comment]
Send to my email or hangouts

**Comment by SplashitApp** [comment]
Issue is with URL not with app,
**App not working properly with the following URL**
```
https://drive.google.com/uc?id=xxxxxxxxxxxxxxxx 
https://github.com/xxxx/xxxx/xxxx.json?raw=true
```

**Same JSON file properly works without any error with the following link**
`https://raw.githubusercontent.com/xxxxx/xxxxx/xxxxx.json`

I have also sent you email JSON file on daxxxxxxxxxxxxx12@gmail.com, please ignore the email. Thanks
