### ISSUE TITLE
Ask user to rate the app.

### ISSUE THREAD

**Issue by AlienCreature7** [danimahardhika/wallpaperboard#20]
Can be a really useful and simple feature (Just a suggestion to make the app even better).

**Comment by danimahardhika** [comment]
Added **Rate & Review** to navigation drawer, hope that's enough

**Comment by AlienCreature7** [comment]
Of course! Thanks for listening to my suggestion and adding this! 

_Sent from my Xiaomi Redmi Note 3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
