### ISSUE TITLE
Not limit category indicators to 99

### ISSUE THREAD

**Issue by AlienCreature7** [danimahardhika/wallpaperboard#21]
for large wallpaper apps like mine which all categories have way more than 100 walls in them those indicators are basically useless but if they would show up to 1000 or even more it would be great. (Suggestion)

**Comment by danimahardhika** [comment]
Doesn't looks good, the text will be too long

**Comment by AlienCreature7** [comment]
How about the ability to enable or disable it? For my app (and probably many others) that has lots of walls this indicators all show 99+ which is not really helpful

**Comment by danimahardhika** [comment]
Not inside filter dialog

**Comment by AlienCreature7** [comment]
I meant in dashboard configurations xml file

**Comment by danimahardhika** [comment]
I mean it will not looks good if applied inside filter by category dialog. I'm not going to change this. Complete number of wallpapers included in each category should be shown somewhere else.
