### ISSUE TITLE
Remove category after json loaded to the app

### ISSUE THREAD

**Issue by AlienCreature7** [danimahardhika/wallpaperboard#27]
If the new json file conflicts with the older one suggest the user to clear cache. in my experience if i change the library file too much the app gets confused and doesnt really update some of the walls and doesnt put them in the right now category so this feature can be really helpful. (Suggestion)

**Comment by danimahardhika** [comment]
@AlienCreature7 What do you mean? Change json url after the app installed?

**Comment by AlienCreature7** [comment]
Currently if the json categories change too much ,like being deleted, it won't be detected by the app fully so the result is that there are some extra categories on the app which are not on the json file anymore and some of these categories don't have anything in them. 

Wallpaperboard should check the json categories smarter.

_Sent from my Xiaomi Redmi Note 3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by danimahardhika** [comment]
Check release [1.2.8](https://github.com/danimahardhika/wallpaperboard/releases/tag/1.2.8)
