### ISSUE TITLE
Firebase Integration for Notification + Data Collection

### ISSUE THREAD

**Issue by motionwallpapers** [danimahardhika/wallpaperboard#30]
I think firebase is the best way to go for custom notification for new wallpaper updates

**Comment by AlienCreature7** [comment]
https://github.com/danimahardhika/wallpaperboard/issues/23

**Comment by danimahardhika** [comment]
I don't want to use background service. Users will open the app if they want to see new wallpapers.

The purpose of this app is to provide the simplest way to display wallpapers for wallpaper designer, the answer is json. Firebase is different.
