### ISSUE TITLE
Apply wallpaper only on lockscreen

### ISSUE THREAD

**Issue by AlienCreature7** [danimahardhika/wallpaperboard#31]

**Comment by motionwallpapers** [comment]
I dont think users will be using this feature alot , unless they want different wallpapers for lockscreen and background

**Comment by AlienCreature7** [comment]
Some people need it. I personally prefer how it works on Google's"wallpapers" app. You see 3 options when you want to apply! Lockscreen only, home screen only & both! It has more choices and is way more easy to use than the way it's handled on wallpaper board.

_Sent from my Xiaomi Redmi Note 3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
