### ISSUE TITLE
[Request] Kustom widget

### ISSUE THREAD

**Issue by marcogenovese** [danimahardhika/wallpaperboard#33]
Is it possible to add support for KWGT widget like on polar dashboard?
I created an app for widgets and wallpapers using Polar but is too buggy and not so much supported.
I really like this app and I would like to switch to this. I tried myself to port code for kustom in polar to this project but is too much for my level..

**Comment by danimahardhika** [comment]
This is wallpaper dashboard, just wallpaper, polar is icon pack dashboard
