### ISSUE TITLE
Crashes instantly upon launch

### ISSUE THREAD

**Issue by Technologx** [danimahardhika/wallpaperboard#34]
I have users and I experienced myself with android 5.1.1+ the app crashes instantly upon launch

**Comment by danimahardhika** [comment]
Post the logcat from developer console here, so I can take a look into it.

**Comment by Technologx** [comment]
Alright I'll have to run it from AS instead of my phone itself.

**Comment by Technologx** [comment]
It does fine without license check turned on when its on it crashes.

https://ghostbin.com/paste/pe69n

**Comment by Technologx** [comment]
Do you think it has something to do with the salt?

**Comment by danimahardhika** [comment]
@Technologx Did you try it on emulator?

**Comment by Technologx** [comment]
@danimahardhika I haven't tried that because it takes forever to load

**Comment by danimahardhika** [comment]
Try to install the demo app from here https://play.google.com/store/apps/details?id=com.dm.wallpaper.board.demo

The logcat is unclear
