### ISSUE TITLE
Wallpapers sorting

### ISSUE THREAD

**Issue by marcogenovese** [danimahardhika/wallpaperboard#35]
For example if I have Wall (1), Wall (2), Wall(3), Wall (4), Wall (5). The showed list is not correct: Wall (5), Wall (3), Wall (4), Wall (2), Wall (1).
And is it possibile to sort in ascending order 1,2,3.. or don't sorting and follow list on json file?

**Comment by danimahardhika** [comment]
Wallpaper sorted by datetime added to database. The process is so fast, sometimes one wallpaper has same datetime with another one.

Example, you have list: Wall (1), Wall (2), Wall(3), Wall (4), Wall (5). Then you add new wallpaper, you can place new wallpaper anywhere inside the list, ex: Wall (1), Wall (2), Wall(6), Wall(3), Wall (4), Wall (5). Wall(6) will be placed on top inside the app.

**Comment by marcogenovese** [comment]
Is there a way to sort wallpapers by name?

**Comment by danimahardhika** [comment]
No, latest added wallpaper should be placed on top

**Comment by AlienCreature7** [comment]
Yeah it's how it works now but if there was an option to sort the wallpapers based on title it would be cool. But it's not much needed I think.  

_Sent from my Xiaomi Redmi Note 3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by marcogenovese** [comment]
Ok, for my collection I can't use this dashboard but thank you anyway.
