### ISSUE TITLE
Elegant way to display total wallpapers above 99 in each category

### ISSUE THREAD

**Issue by motionwallpapers** [danimahardhika/wallpaperboard#37]
In my wallpapers app , some categories have more than 1000 wallpapers
but now it shows only 99+ , i understand it best for the design ,it will be great if it can be adapted to 

0 - 999
the 1K , 1.5K , 10K etc

http://imgur.com/oQRxDkt

**Comment by xorRisont** [comment]
Just edit FilterAdapter.java:86
`String count = category.getCount() > 99 ? "99+" : category.getCount() +"";` 
to
`String count = category.getCount() > 999 ? "999+" : category.getCount() +"";`

**Comment by motionwallpapers** [comment]
but having 999+ in the same small circle will create design issues

**Comment by xorRisont** [comment]
> but having 999+ in the same small circle will create design issues

Then set in **layout\fragment_filter_item_list.xml:id=counter**
`android:layout_width="32dp"`
`android:layout_height="32dp"`
This will increase bubbles
