### ISSUE TITLE
Total number of wallpapers not showing

### ISSUE THREAD

**Issue by motionwallpapers** [danimahardhika/wallpaperboard#38]
Total number of wallpapers not showing when above 1000 wallpapers

http://imgur.com/a/nyb90
(second image)

**Comment by danimahardhika** [comment]
Duplicate https://github.com/danimahardhika/wallpaperboard/issues/37

**Comment by danimahardhika** [comment]
The problem not comes from number of wallpapers, everything works fine, wallpaper count still showed 99+. Make sure to add matches category name.
