### ISSUE TITLE
Splashscreen issue

### ISSUE THREAD

**Issue by wilfredparmar** [danimahardhika/wallpaperboard#39]
Hello Dani Mahardhika.
Great work.
i want help. i want to put full screen FHD wallpaper on splash screen. so please help me with that. i tried to put wallpaper but it appears very small like icon. and also want to change text appearing at the last.
i tired finding code but couldn't get where to customize that.
please refer screenshot.

![screenshot_20170614-134457](https://user-images.githubusercontent.com/29352333/27122472-78f7bb14-5108-11e7-9329-503c4f5d6333.png)

Thank you.

**Comment by danimahardhika** [comment]
Splash screen not designed that way, you need to modify the library by yourself, butt don't ask me how.

Splash screen text
https://github.com/danimahardhika/wallpaperboard/wiki/Customization:-Advanced#6-splash-screen-text

**Comment by wilfredparmar** [comment]
ok thank you for text. 
i already read that week ago. but i forget that.

 i'll figure out. Thank you.
