### ISSUE TITLE
Filter by Category

### ISSUE THREAD

**Issue by wilfredparmar** [danimahardhika/wallpaperboard#40]
I have many categories in my app. By default they all are selected. 
 if i want to view wallpaper of particular category then i have to uncheck all of them.
For example : i have 50 categories of wallpapers. if i want to see walls of particular one category then i have to uncheck 49 categories.
can u make changes to that? 
because we have to first uncheck all to just view one category.

**Comment by marcogenovese** [comment]
Select all/unselect all check box  on top should be good

**Comment by wilfredparmar** [comment]
that should be good if there is only few categories. but what is there are so many?

**Comment by motionwallpapers** [comment]
Select all/unselect all check box on top
