### ISSUE TITLE
Unable to remove "Support Developement" from navigation drawer

### ISSUE THREAD

**Issue by EpikurProd** [danimahardhika/wallpaperboard#42]
I want to disable "support developement" from navigation drawer on a published free app, i turned off in dashboard_configurations.xml (<bool name="enable_donation">false</bool>). When i want to test my app "support developement" still in navigation drawer, but "Rate App" disappear. I only see "Share App" below "sup. dev". I try in debug version with license checker Off. I try also on signed version with license checker ON (true on license.java) and publish on PlayStore but same issue. I can add a screenshot if necessary. Thanks in advance.

**Comment by danimahardhika** [comment]
Duplicate https://github.com/danimahardhika/wallpaperboard/issues/32
