### ISSUE TITLE
Adding admob

### ISSUE THREAD

**Issue by Th3CracKed** [danimahardhika/wallpaperboard#43]
I want to add admob can you please guide me i want to ad interstitial in the transition to select a wallpaper

**Comment by AlienCreature7** [comment]
It's pretty hard. He even helped me a little bit via email but still I couldn't make it work. 

_Sent from my Xiaomi Redmi Note 3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Th3CracKed** [comment]
yes i forked his library and try to make changes but i still can't add admob
the app is very clean i would like a version with admob and without category filter

**Comment by motionwallpapers** [comment]
I guess adding abmob wont a good idea . This project is cool because its light weight , zero ads and fast loading . Adding admob will slow down everything and will take away the beauty of the project

**Comment by danimahardhika** [comment]
The library is open source, you can do whatever you want. But I won't add an option to enable ads. If you want to add admob you need to modify the library by yourself.

**Comment by Th3CracKed** [comment]
thank you for your quick response but i tried to add the admob and i can't find where the code of transition beetwen activity

**Comment by danimahardhika** [comment]
[WallpapersAdapter.java](https://github.com/danimahardhika/wallpaperboard/blob/master/library/src/main/java/com/dm/wallpaper/board/adapters/WallpapersAdapter.java)
