### ISSUE TITLE
How to Change Design Of Application

### ISSUE THREAD

**Issue by arjunmaan2011** [danimahardhika/wallpaperboard#44]
I want to Change design of application with my own gui with large images and Icons Etc, and different activity for category list.

**Comment by danimahardhika** [comment]
Download sample app, import the library as project. If you want to modify the library you need to figure it out by yourself.

**Comment by arjunmaan2011** [comment]
Thanks One Last Question My Json file output from php wallpapers fetched from database contains url like this `https:\/\/wallpapers.wallhaven.cc\/wallpapers\/full\/wallhaven-29807.jpg` and App Forcefully Closes What should i do

**Comment by danimahardhika** [comment]
If your json comes from php then you can't used it. It's different, the problem not comes from the wallpaper url. Wait until next release, I'll add an option for this.

**Comment by arjunmaan2011** [comment]
Thanx.

**Comment by danimahardhika** [comment]
@arjunmaan2011  Just want to make sure, please post the logcat when the app crash here so I can check into it

**Comment by arjunmaan2011** [comment]
Implement google ads and Firebase Based Notifications. Or My Brother Implement it and he post here on git hub Updated Code For WallpaperBoard.

**Comment by danimahardhika** [comment]
I'm going to close this issue, check https://github.com/danimahardhika/wallpaperboard/issues/46 to track json support from php

**Comment by danimahardhika** [comment]
@arjunmaan2011 Check release [1.3.0](https://github.com/danimahardhika/wallpaperboard/releases/tag/1.3.0)
