### ISSUE TITLE
Wallpaper on always applied on the lockscreen 

### ISSUE THREAD

**Issue by xorRisont** [danimahardhika/wallpaperboard#47]
Regardless of the wallpaper's setting. 
Android 7.x
This issues is also in candybar

**Comment by danimahardhika** [comment]
It should be disabled in Wallpaper Setting

There's no problem with the code
```java
if (Preferences.get(context).isApplyLockscreen() && Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
    manager.setBitmap(bitmap, null, true, WallpaperManager.FLAG_LOCK | WallpaperManager.FLAG_SYSTEM);
} else {
    manager.setBitmap(bitmap);
}
```

**Comment by xorRisont** [comment]
> It should be disabled on Wallpaper Setting

When i disable in Walppaper Setting - wallpaper anyway applies  on the lockscreen

**Comment by danimahardhika** [comment]
@xorRisont What device are you using? Do you use custom rom?

**Comment by xorRisont** [comment]
> What device are you using? Do you use custom rom?

on 2 devices:
Nexus 6P | Nitrogen OS 7.1.2
OnePlus 3T | stock rom

**Comment by danimahardhika** [comment]
@xorRisont Did you modify the library?

**Comment by xorRisont** [comment]
@danimahardhika 
> Did you modify the library?

Yes, but i have this trouble in WallpaperBoard Demo (from Google Play)
I can make video demonstration

**Comment by danimahardhika** [comment]
@xorRisont I'm using lg g5 with nougat, everything works fine. Try to clear data.

**Comment by xorRisont** [comment]
@danimahardhika on Galaxy S8 and J5 this bug too. 
Clear appdata doesn't help

**Comment by xorRisont** [comment]
WORKS! 
I changed (WallpaperHelper.java:521):

`if (Preferences.get(context).isApplyLockscreen() && 
Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
    manager.setBitmap(bitmap, null, true, WallpaperManager.FLAG_LOCK | WallpaperManager.FLAG_SYSTEM);
} else {
    manager.setBitmap(bitmap);
}`

**to**

`if (Preferences.get(context).isApplyLockscreen() &&
                                    Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
                                manager.setBitmap(bitmap, null, true, WallpaperManager.FLAG_LOCK | WallpaperManager.FLAG_SYSTEM);
                            } else if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N){
                                manager.setBitmap(bitmap, null, true, WallpaperManager.FLAG_SYSTEM);
                            }`

**Comment by danimahardhika** [comment]
This one is better @xorRisont, I'll fix this soon
```java
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
    if (Preferences.get(context).isApplyLockscreen()) {
        manager.setBitmap(bitmap, null, true, WallpaperManager.FLAG_LOCK | WallpaperManager.FLAG_SYSTEM);
        return true;
    }

    manager.setBitmap(bitmap, null, true, WallpaperManager.FLAG_SYSTEM);
    return true;
}

manager.setBitmap(bitmap);
return true;
```
