### ISSUE TITLE
Add in app as Fragment

### ISSUE THREAD

**Issue by BRoy98** [danimahardhika/wallpaperboard#50]
I have an app that has some others functionalities and I want to add wallpaperboard in it for a separate wallpaper section. But I do not want to add as a new activity. Is there any way to add wallpaperboard as a fragment?

**Comment by danimahardhika** [comment]
WallpaperBoard is open source, you can see and take the code in it. But if you don't know about programming, then it's too hard to explain here. If you want to modify the dashboard, you need to do it by yourself.

**Comment by BRoy98** [comment]
Aaah I know that. I am just asking if there is any default configuration already available for fragment support.
