### ISSUE TITLE
wallpaper  grid style is not changing

### ISSUE THREAD

**Issue by irshad2809** [danimahardhika/wallpaperboard#51]
configuration.setWallpapersGridStyle(GridStyle.CARD);

i changed the grid style using this config , but it doesn't do anything. 

2) also can you guide me for interchanging the position of download and set wallpaper buttons?

**Comment by danimahardhika** [comment]
1. Everything works fine. There's only a small difference. Try to use the flat one first, then change it to card, after that compare them.

2. Check [fragment_wallpaper_options.xml](https://github.com/danimahardhika/wallpaperboard/blob/master/library/src/main/res/layout/fragment_wallpaper_options.xml)
