### ISSUE TITLE
My JSON file is being ignored for some reason

### ISSUE THREAD

**Issue by JABBERWOCK1** [danimahardhika/wallpaperboard#56]
My JSON file is being ignored for some reason,  how may i get some help on this or do you have a suggestion for course of action?  I am using Google Drive for the pics,thumbs and json, would that make a difference for some reason? and using different config like no author etc.. can I just do "" or do I need to do that  "(null)" config you specified, or easier just put a placeholder name or character till I can get it working, or even after. My Google directory and file are marked as public for viewing, initially I just pointed it to the directory, but lately have tried acquiring links directly to each file, still not working though. I noticed the action is didderent on the json, from your link it starts to attempt a download of it, on mine from Google drive it does not, maybe that could be the problem? how would I fix that? better host for the files?

**Comment by danimahardhika** [comment]
I don't really understand what do you mean, please give more explanation.

**Comment by JABBERWOCK1** [comment]
I have attached my json file, if there are any other files that would help for you to see just state that.
I have used the Android studio to follow your step by step tutorial, and customized all I could until such a time I could join the Google store developers and get pictures to use.  My customization in the Dashboardconfigurations.xml all work fine, but it was still linking to the original pictures, once I got the pictures collected , thumbnails and json file together I uploaded all that to my google drive and updated 
the link in the dashoardconfigurations.xml in order to reference my json file, my link in that file oddly enough does not prompt a download of the json but an actual view, I don't know if that is a function of my pc or if it is an inaction caused by google drive, even odder to me is the fact that on my phone it still loads the pics from the old json file link even though I have changed it (i.e. Meru West, Tanza... Elliot Engelmann etc...) So I must be missing something easy and obvious but am unsure as to which area could be causing the problem, or is it a combination of things
[wallpaper_sample(1) (1).zip](https://github.com/danimahardhika/wallpaperboard/files/1234696/wallpaper_sample.1.1.zip)

**Comment by danimahardhika** [comment]
1. Your google drive url is not valid. That's not a direct url. This is an example of valid url [`https://drive.google.com/uc?id=0B4Pj9XZHPS5hUi0zX3FoRTFCTEE`](https://drive.google.com/uc?id=0B4Pj9XZHPS5hUi0zX3FoRTFCTEE)
2. Your wallpaper json structure is not valid. Author must be defined. If you want to use auto generated wallpaper name. You must defined custom wallpaper json, check [here](https://github.com/danimahardhika/wallpaperboard/wiki/Wallpaper-Json-Structure) for more info. This is an example:
```java
Configuration configuration = new Configuration();
...
configuration.setJsonStructure(
        new JsonStructure.Builder()
                .categoryStructure(
                        new JsonStructure.CategoryStructure("Categories"))
                .wallpaperStructure(
                        new JsonStructure.WallpaperStructure("Wallpapers")
                                .name(null))
                .build());
```
