### ISSUE TITLE
Which repo i have to use

### ISSUE THREAD

**Issue by L0nelyW0lf** [danimahardhika/wallpaperboard#58]
Very Confused on which one i have to use to develop my app
Wallpaperboard Master or
Wallpaperboard sample ?

If Wallpaperboard master have to be used i cant able to run that.
Need Help

thank you

**Comment by danimahardhika** [comment]
Sample, read the wiki site before asking https://github.com/danimahardhika/wallpaperboard/wiki

**Comment by L0nelyW0lf** [comment]
ok if i want to do this #43 i cant find that particular file in sample

**Comment by danimahardhika** [comment]
If you want to add admob, you need to modify the library by yourself and don't ask me how.
