### ISSUE TITLE
Quick shortcuts

### ISSUE THREAD

**Issue by AlienCreature7** [danimahardhika/wallpaperboard#59]
(enhancement) quick shortcuts for favorites, a random wallpaper etc. Would be cool.

**Comment by danimahardhika** [comment]
If you want shortcut on android 7.1, you need to add in your app (sample). It won't works if added in library.

**Comment by danimahardhika** [comment]
Check here https://github.com/danimahardhika/wallpaperboard/wiki/Create-App-Shortcuts-on-Android-7.1

**NOTE:** This is only works with latest snapshot and release after 1.3.1
