### ISSUE TITLE
Download Count

### ISSUE THREAD

**Issue by L0nelyW0lf** [danimahardhika/wallpaperboard#60]
It will be good if you download count.

**Comment by danimahardhika** [comment]
I don't understand what do you mean, please give more explanation.

**Comment by L0nelyW0lf** [comment]
like how many times a wallpaper is downloaded

**Comment by danimahardhika** [comment]
This is just a json based wallpaper dashboard. That's not possible to detect the download count.

**Comment by vajiralasantha** [comment]
You will need an API for this. I'm currently building a PHP API for one of my wallpaper app and I will try to integrate it to this app as well.

**Comment by danimahardhika** [comment]
@kingofwap What @vajiralasantha said is right.

I just provide the simple way to build your own wallpaper app based on json. The dashboard is open source you can modify it based on your needs.

**Comment by L0nelyW0lf** [comment]
yes got it. thank you
