### ISSUE TITLE
Translation: Sepatare number of wallpapers from navigation_view_wallpapers

### ISSUE THREAD

**Issue by hanubeki** [danimahardhika/wallpaperboard#68]
I want to translate number of wallpaper like "23枚の壁紙", but that currently uses navigation_view_wallpapers which is also used for navigation menu that I don't want to change.
So I would like to separate a string for number of wallpapers from navigation_view_wallpapers.

**Comment by danimahardhika** [comment]
I don't understand what do you mean?

**Comment by hanubeki** [comment]
I want to translate "xxx Wallpapers" (wallpapers count) in category view to "xxx枚の壁紙", but "Wallpapers" in navigation drawer remains "壁紙".

**Comment by danimahardhika** [comment]
Is that different? Just translate the wallpapers word

**Comment by hanubeki** [comment]
I thought that was different in Japanese, but closing the issue for now.
