### ISSUE TITLE
New Wallpapers Chip Showing even when there are no new Wallpapers

### ISSUE THREAD

**Issue by DarinMenezes** [danimahardhika/wallpaperboard#7]
The new Wallpapers thingy keeps appearing on every app launch

**Comment by danimahardhika** [comment]
* Check new wallpapers runs alongside with loading wallpapers for the first time. It's possible that check new wallpaper finished before all wallpapers loaded which makes popup bubble of new wallpaper keep showing.
* Check new wallpaper runs on background, if you have more than 1 app using same dashboard, it's possible the info about number of wallpapers mixed which also makes popup bubble of new wallpaper keep showing.

**Temporary Fix:** Just refresh wallpapers or press the popup bubble, it will be hidden after that.
