### ISSUE TITLE
Hide size part if wallpaper size is unknown

### ISSUE THREAD

**Issue by NikiHard** [danimahardhika/wallpaperboard#70]
does not display the file size ... it's with all the wallpaper
![scrin](https://user-images.githubusercontent.com/14994565/30204590-a92388bc-948e-11e7-8c4e-33b3898840a9.jpg)

**Comment by danimahardhika** [comment]
Post the wallpaper url here, and I'll check that.

**Comment by NikiHard** [comment]
https://porting-team.ru/wp-content/uploads/2017/09/flowers_peonies_bicycle_hand_117104_5472x3648.jpg

**Comment by danimahardhika** [comment]
The site doesn't returns file size, that's the reason. Negative value means the size is unknown. The only way to obtain file size is downloading the image first. It's a bit complicated to explain, but it's not really the dashboard fault. I'll just hide that part if size is unknown.

**Comment by NikiHard** [comment]
Maybe I should transfer the size to json?

**Comment by NikiHard** [comment]
Maybe I should transfer the size to json?

**Comment by danimahardhika** [comment]
No, the dashboard won't read that.

**Comment by danimahardhika** [comment]
Check release [1.5.2](https://github.com/danimahardhika/wallpaperboard/releases/tag/1.5.2)
