### ISSUE TITLE
 Could not find TapTargetView.jar 

### ISSUE THREAD

**Issue by motionwallpapers** [danimahardhika/wallpaperboard#74]
A new error came in a sudden any idea ? i think its the animation ?
Error:A problem occurred configuring project ':app'.
> Could not find TapTargetView.jar (com.github.KeepSafe:TapTargetView:-SNAPSHOT).
Searched in the following locations:
https://jitpack.io/com/github/KeepSafe/TapTargetView/-SNAPSHOT/TapTargetView--1.9.1-g42284f9-12.jar

Internet connection was there . I was watching youtube videos. 

and the link above . https://jitpack.io/com/github/KeepSafe/TapTargetView/-SNAPSHOT/TapTargetView--1.9.1-g42284f9-12.jar is NOT FOUND

**Comment by motionwallpapers** [comment]
![capture](https://user-images.githubusercontent.com/29356172/30302888-a8ced71c-977d-11e7-97e0-d98ec1826590.PNG)

**Comment by danimahardhika** [comment]
@motionwallpapers Which version of WallpaperBoard are you using?

**Comment by motionwallpapers** [comment]
1.3.1
Just checked all my 3 apps , all showing the same error

**Comment by danimahardhika** [comment]
@motionwallpapers Take a look on this post https://github.com/danimahardhika/candybar-library/issues/91#issuecomment-328709771

**Comment by AlienCreature7** [comment]
as far as I understood the link is broken for some reason. only people who have the file in their cache can build the app without error.

**Comment by besidesordinary** [comment]
I tried danimahardhika/candybar-library#91 (comment)

But this was the result... :(

I am using  wallpaperboard:1.3.1

Run with --stacktrace option to get the stack trace. Run with --info or --debug opti
on to get more log output.

BUILD FAILED

Total time: 1 mins 26.778 secs

**Comment by danimahardhika** [comment]
@besidesordinary You need to update to release 1.5.6

**Comment by besidesordinary** [comment]
Thank you! Now https://jitpack.io/com/github/KeepSafe/TapTargetView/-SNAPSHOT/TapTargetView--1.9.1-g42284f9-12.jar has been FIXED! 👍 :)

**Comment by motionwallpapers** [comment]
@danimahardhika  What if not to update to 1.5.6 ? cannot update the app forever ?

**Comment by besidesordinary** [comment]
Does anyone know where and how to customize the order of the Wallpapers menu. 

For example, the wallpaper's grid to be shown first when you launch the app. Then swipe for the categories etc. 

Any help would be greatly appreciated!
Thank you!

**Comment by danimahardhika** [comment]
@motionwallpapers Yes you need to update to 1.5.6

@besidesordinary Open a new issue if you want to ask something, don't just asking inside another issue which is not related at all.

**Comment by besidesordinary** [comment]
Ok, i'll go ahead and do that, sorry for the mistake...

**Comment by motionwallpapers** [comment]
@danimahardhika i really like the old design , i have forked your code , can i change anything in my forked code and make it work with 1.3.1 , the old design is very important for me

**Comment by danimahardhika** [comment]
@motionwallpapers The issue happened because there's a problem with the site where library is hosted. The site doesn't respond to old release, I made a changes to trigger the site to rebuild the project again. So to put simply, you need to update to latest release.

If you want to use old release, you need to modify the library, go to release site https://github.com/danimahardhika/wallpaperboard/releases, search for specific version you want to use, then download source code.

But don't ask me how to do that, it's a long and complicated story.
