### ISSUE TITLE
Muzei Settings don't open

### ISSUE THREAD

**Issue by AlienCreature7** [danimahardhika/wallpaperboard#77]
It works on my apps based on older versions of Wallpaperboard. I can't make it work on the latest version now. I am not really sure if I've done something wrong or it's a bug.

**Comment by danimahardhika** [comment]
https://github.com/danimahardhika/wallpaperboard/wiki/Setup#open-androidmanifestxml

**Comment by AlienCreature7** [comment]
yeah it was my fault. ;-;

**Comment by AlienCreature7** [comment]
yeah it was my fault. ;-;
