### ISSUE TITLE
Add Admob Integration 

### ISSUE THREAD

**Issue by MohdShamim111** [danimahardhika/wallpaperboard#80]
Possible to add admob in this library

**Comment by danimahardhika** [comment]
You need to modify the library by yourself

**Comment by MohdShamim111** [comment]
Ok

On Sep 19, 2017 12:31 PM, "Dani Mahardhika" <notifications@github.com>
wrote:

You need to modify the library by yourself

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/danimahardhika/wallpaperboard/issues/80#issuecomment-330448586>,
or mute the thread
