### ISSUE TITLE
Better anti piracy 

### ISSUE THREAD

**Issue by AlienCreature7** [danimahardhika/wallpaperboard#82]
(Enhancement) My apps are being pirated and I can't even do anything about it. There must be a way to solve this problem.

**Comment by KaustubhPatange** [comment]
Dexguard will help you to obfuscate some part of your code hardly http://www.saikoa.com/dexguard

**Comment by KaustubhPatange** [comment]
@AlienCreature7 Although your question does not belong to this board or this type

**Comment by danimahardhika** [comment]
@KaustubhPatange The dashboard already use proguard, dexguard is paid so it's a different story.
@AlienCreature7 Just stop complaining. People who always buy will always buy.

**Comment by AlienCreature7** [comment]
@danimahardhika yeah I know people who buy will buy but still

**Comment by AlienCreature7** [comment]
@danimahardhika yeah I know people who buy will buy but still
