### ISSUE TITLE
Monetizing using either Ad-Banners or Interstitial Ads

### ISSUE THREAD

**Issue by genzcodersz** [danimahardhika/wallpaperboard#84]
I'm sure lot of users want this as any designer who creates a wallpaper obviously expects more than just a donation. I think it'll be good if you implement Google admob and inside dashborad.xml, add an example string like  "Ad-Banner: xxxxxx"/Interstitial-Ad: xxxxxx" so any user who decides on putting up ads can simply edit it with their ad-unit or leave it blank if they don't want to publish their app with ads.

**Comment by genzcodersz** [comment]
Okay so I just went through previous topics and seems like this has already been discussed. I shall make an effort of implementing ads by myself and publish the library for others to use. Thanks for your efforts though.

**Comment by danimahardhika** [comment]
I just want the library keep clean, at the moment. If you want ads, you can modify the library by yourself.
