### ISSUE TITLE
Ignored thumbUrl

### ISSUE THREAD

**Issue by eskalera** [danimahardhika/wallpaperboard#90]
I've used my own json with the exact same structure as the default.
The only thing I've done so far is changing the url and thumbUrl fields of the "Flowers with peonies bicycle" with my own urls.

When I launch the app, the preview image is still the "flowers and peonies" but when I click on it I can see my own photo.

I've already cleaned the cache. Also completely uninstalled the app but the thumb won't change.

I even inspected the sqlite db and I can see how the field thumbUrl is still the one with "flowers and peonies".

What am I missing?!

**Comment by danimahardhika** [comment]
It will be helpful if you can provide more info, like the json url or something.

**Comment by eskalera** [comment]
Wow! Thanks for the blazing fast reply.

And also sorry. Now I was going to give you the url for my json I realised it still had the old thumbUrl. I was updating the json in my Google Drive, but I didn't know the URL from Drive changed every time I updated it.

Solved. Thanks.
