### ISSUE TITLE
Email Enhancements 

### ISSUE THREAD

**Issue by genzcodersz** [danimahardhika/wallpaperboard#93]
Add this to the "AboutSocialAdaptor.java" > email

   `      

                        if (type == UrlHelper.Type.EMAIL) {      
  
                        try {

                        String deviceInfo="------------ Device Info ------------";

                        deviceInfo += "\n OS Version: " + System.getProperty("os.version") + "(" + android.os.Build.VERSION.INCREMENTAL + ")";

                        deviceInfo += "\n OS API Level: " + android.os.Build.VERSION.SDK_INT;

                        deviceInfo += "\n Device: " + android.os.Build.DEVICE;

                        deviceInfo += "\n Board: " + android.os.Build.BOARD;

                        deviceInfo += "\n Hardware: " + android.os.Build.HARDWARE;

                        deviceInfo += "\n Build ID: " + android.os.Build.ID;

                        deviceInfo += "\n Device Brand: " + android.os.Build.BRAND;

                        deviceInfo += "\n Device Manufacturer: " + android.os.Build.MANUFACTURER;

                        deviceInfo += "\n Model (and Product): " + android.os.Build.MODEL + " ("+ android.os.Build.PRODUCT + ")";

                        deviceInfo += "\n ---------------------------------------------";
                      
                        final Intent email = new Intent(Intent.ACTION_SENDTO, Uri.fromParts(
                                "mailto", mUrls[position], null));
                        email.putExtra(Intent.EXTRA_TEXT,deviceInfo);`

So any user who sends an email with bug report or feature request, the email will attach their device data. This will be handy to fix bugs and to know the insights of the device cause usually people don't provide their device details.

Demo :

![ss](https://user-images.githubusercontent.com/7279710/31450410-f4dc6d80-aec6-11e7-97fb-5b69d86c6135.jpg)

**Comment by danimahardhika** [comment]
The dashboard already contains crash report, just make sure to add your email in social url, so this is **not needed**.
