### ISSUE TITLE
No apply on homescreen button if the app is installed on SD Card

### ISSUE THREAD

**Issue by AlienCreature7** [danimahardhika/wallpaperboard#94]
It didnt show the apply on screen option for me, i moved the app to internal storage and it got fixed.

**Comment by danimahardhika** [comment]
It's working fine, just tried it

**Comment by AlienCreature7** [comment]
i think disabling the downloads causes this to happen sometimes. I now tried and on my new app it has the same problem. it's sometimes appearing in some places but sometimes it just doesn't. I had the same problem on my other app which had downloads disabled.

**Comment by AlienCreature7** [comment]
I just sent you a few screenshots of the bug to you on hangouts
