### ISSUE TITLE
Admob integration

### ISSUE THREAD

**Issue by NikiHard** [danimahardhika/wallpaperboard#95]
Can you tell me how to connect [this](https://github.com/clockbyte/admobadapter)?

I've been trying for a week and I still do not get out
![screenshot_1507760863](https://user-images.githubusercontent.com/14994565/31579116-bd934862-b137-11e7-82e1-4650874addb5.jpg)

**Comment by danimahardhika** [comment]
Reduce the adapter position by one. 
If you want to modify the library you need to figure it out by yourself.

**Comment by NikiHard** [comment]
Please tell me where it can be done where it can be done?

**Comment by NikiHard** [comment]
Thank you for the wallpaperboard, I did it)) [my app ](https://play.google.com/store/apps/details?id=com.pt.wallpaper.board)
