### ISSUE TITLE
Broken "Color Palette" Functionality & Problem with "Search Icon - Adaptive Color" (Core issues)

### ISSUE THREAD

**Issue by genzcodersz** [danimahardhika/wallpaperboard#96]
There is some problem with helpers:core dependency 
Reverting back from SNAPSHOT (0.0.8) release to 0.0.7 fixes it for now.

Build.gradle (library) - Version 1.6.0
`compile 'com.github.danimahardhika.android-helpers:core:0.0.7'`

# **SNAPSHOT (0.0.8) version :** 

![screenshot_20171018-202609](https://user-images.githubusercontent.com/7279710/31726200-e6ed4744-b443-11e7-936f-32a623d8ceba.png)
![screenshot_20171018-202618](https://user-images.githubusercontent.com/7279710/31726211-eeb4d550-b443-11e7-97de-c75210ccf7f1.png)

# **After reverting back :** 

![screenshot_20171018-203012](https://user-images.githubusercontent.com/7279710/31726246-09caaa7c-b444-11e7-8d73-e6d495357492.png)
![screenshot_20171018-203020](https://user-images.githubusercontent.com/7279710/31726257-109a9614-b444-11e7-8989-055215607f72.png)

**Comment by danimahardhika** [comment]
Fixed https://github.com/danimahardhika/android-helpers/issues/1
