### ISSUE TITLE
Gradle script not compatible with gradle tools 3.0.0

### ISSUE THREAD

**Issue by rigwarlsback** [danimahardhika/wallpaperboard#97]
https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html#variant_api

I was using Android Studio v2.3.3 and I updated to the latest release with the newer gradle version, since then I cannot sync because of the outputFileName issue. 

Is there a workaround? I'm moving back to 2.3.3 for now.

**Comment by xorRisont** [comment]
just comment that
>     android.applicationVariants.all { variant ->
>         variant.outputs.each { output ->
>             def file = output.outputFile
>             def appName = parent.name
>             def fileName = appName.replace(" ", "_") + "_v" + variant.versionName + ".apk"
>             output.outputFile = new File(file.parent, fileName)
>         }
>     }
or learn more about Gradle 3

**Comment by danimahardhika** [comment]
Yes, just remove that. The code used to rename generated signed apk based on your project name and version number. I'll take a look into it and find some alternative.

**Comment by danimahardhika** [comment]
Open root `build.gradle` then

Replace this
```gradle
android.applicationVariants.all { variant ->
    variant.outputs.each { output ->
        def file = output.outputFile
        def appName = parent.name
        def fileName = appName.replace(" ", "_") + "_v" + variant.versionName + ".apk"
        output.outputFile = new File(file.parent, fileName)
    }
}
```

**Edit:** with this
```gradle
android.applicationVariants.all { variant ->
    variant.outputs.all { output ->
        def appName = parent.name
        def fileName = appName.replace(" ", "_")
        outputFileName = "$fileName-v${variant.versionName}.apk"
    }
}
```

**Comment by rigwarlsback** [comment]
_Using the Variant API to manipulate variant outputs is broken with the new plugin. It still works for simple tasks, such as changing the APK name during build time, as shown below:_ take a look at this line from the migration guide, also Dani, I tried doing it like you suggested and as the migration guide says, the problem is that no single apk is being generated. For now I had to roll back to 2.3.3 which works like it is supposed to.

**Comment by danimahardhika** [comment]
This one should works 
```gradle
android.applicationVariants.all { variant ->
    variant.outputs.all { output ->
        def appName = parent.name
        def fileName = appName.replace(" ", "_")
        outputFileName = "$fileName-v${variant.versionName}.apk"
    }
}
```
Generated signed apk located inside release folder

**Comment by danimahardhika** [comment]
Check release [1.7.0-b1](https://github.com/danimahardhika/wallpaperboard/releases/tag/1.7.0-b1)
