### ISSUE TITLE
Fast scrollbar?

### ISSUE THREAD

**Issue by rigwarlsback** [danimahardhika/wallpaperboard#98]
The side scrollbar in the recycler gridview does not do a fast scroll. Can we implement something like a fast scroll bar where a user can hold the scroll bar and scroll fast if they want to?

**Comment by rigwarlsback** [comment]
https://stackoverflow.com/questions/27798212/how-to-add-a-fast-scroller-to-the-recyclerview

This looks promising

**Comment by danimahardhika** [comment]
No, it's a bit complicated to explain. The dashboard uses swipe refresh layout and app bar scroll, it will needs a nested scrolling. But with nested scrolling enabled fast scroller is a bit  weird, let's say it's not working properly.
